name: Build APK

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle Wrapper
        run: |
          gradle wrapper
          chmod +x gradlew

      # google-services.json ফাইল তৈরি করা
      - name: Create google-services.json
        run: |
          mkdir -p app
          cat << 'EOF' > app/google-services.json
          {
            "project_info": {
              "project_number": "811952393925",
              "firebase_url": "https://frndom-871ec-default-rtdb.firebaseio.com",
              "project_id": "frndom-871ec",
              "storage_bucket": "frndom-871ec.firebasestorage.app"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:811952393925:android:4755f7334040c07c702aac",
                  "android_client_info": {
                    "package_name": "com.frndom"
                  }
                },
                "oauth_client": [],
                "api_key": [
                  {
                    "current_key": "AIzaSyDIyVBiQKM9sFaOie1Mabvx6uWIq_5G2g4"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOF

      # KSP এরর ফিক্স করার ফ্ল্যাগ
      - name: Fix KSP NullPointer in Headless Environment
        run: |
          echo "ksp.useKSP2=false" >> gradle.properties
          echo "ksp.incremental=false" >> gradle.properties

      # এপিকে বিল্ড করা
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: App-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
